### ISSUE TITLE
Issue for creating collection in solrcloud.

### ISSUE THREAD

**Issue by navihr** [OpenSextant/SolrTextTagger#92]
I was run 2 node in solr with single zookeeper to configure. I'll try to create a collection like location Its create successfully and then try to create second collection like contact. Its throw error.

**solr mem size** : 1Gb
**solr version** :  8.6.2

**Config to ZK**

```
    sudo ./zkcli.sh -cmd upconfig -zkhost localhost:2181 -confdir /home/cores/location/conf -confname conf_location
  
     sudo ./zkcli.sh -cmd linkconfig -collection location -confname conf_location -zkhost localhost:2181
     
     sudo ./zkcli.sh -cmd upconfig -zkhost localhost:2181 -confdir /home/ec2-user/cores/contact/conf -confname conf_contact
  
     sudo ./zkcli.sh -cmd linkconfig -collection contact -confname conf_contact -zkhost localhost:2181
```

**Make API Call for create collection**

```
curl -sS 'http://localhost:8983/solr/admin/collections?action=CREATE&name=contact&numShards=2&replicationFactor=2&maxShardsPerNode=2&collection.configName=conf_contact'
```
**Response for create collection**

```JSON
"responseHeader":{
    "status":400,
    "QTime":1154},
  "failure":{
    "192.168.1.121:8983_solr":"org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:Error from server at http://192.168.1.121:8983/solr: Error CREATEing SolrCore 'contact_shard2_replica_n6': Unable to create core [contact_shard2_replica_n6] Caused by: org.opensextant.solrtexttagger.TaggerRequestHandler",
    "192.168.1.121:8983_solr":"org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:Error from server at http://192.168.1.121:8983/solr: Error CREATEing SolrCore 'contact_shard1_replica_n3': Unable to create core [contact_shard1_replica_n3] Caused by: org.opensextant.solrtexttagger.TaggerRequestHandler",
    "192.168.1.157:8983_solr":"org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:Error from server at http://192.168.1.157:8983/solr: Error CREATEing SolrCore 'contact_shard2_replica_n5': Unable to create core [contact_shard2_replica_n5] Caused by: org.opensextant.solrtexttagger.TaggerRequestHandler",
    "192.168.1.157:8983_solr":"org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException:Error from server at http://192.168.1.157:8983/solr: Error CREATEing SolrCore 'contact_shard1_replica_n1': Unable to create core [contact_shard1_replica_n1] Caused by: org.opensextant.solrtexttagger.TaggerRequestHandler"},
  "Operation create caused exception:":"org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Underlying core creation failed while creating collection: contact",
  "exception":{
    "msg":"Underlying core creation failed while creating collection: contact",
    "rspCode":400},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"Underlying core creation failed while creating collection: contact",
    "code":400}}
```

**Solr log**

```
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://192.168.1.121:8983/solr: Error CREATEing SolrCore 'contact_shard1_replica_n3': Unable to create core [contact_shard1_replica_n3] Caused by: org.opensextant.solrtexttagger.TaggerRequestHandler
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:681) ~[?:?]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:266) ~[?:?]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248) ~[?:?]
	at org.apache.solr.client.solrj.SolrClient.request(SolrClient.java:1290) ~[?:?]
	at org.apache.solr.handler.component.HttpShardHandlerFactory$1.request(HttpShardHandlerFactory.java:169) ~[?:?]
	at org.apache.solr.handler.component.ShardRequestor.call(ShardRequestor.java:130) ~[?:?]
	at org.apache.solr.handler.component.ShardRequestor.call(ShardRequestor.java:41) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) ~[metrics-core-4.1.5.jar:4.1.5]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:212) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by dsmiley** [comment]
I suspect the failure is a ClassNotFoundException for org.opensextant.solrtexttagger.TaggerRequestHandler.

If you are using a modern version of Solr, then please use https://lucene.apache.org/solr/guide/8_6/the-tagger-handler.html
Are you using the older version here for some reason?

**Comment by navihr** [comment]
Yeah @dsmiley . Resolve that issue in my side. Now Its working. Thanks @dsmiley .
